// Code generated by protoc-gen-go.
// source: strand.proto
// DO NOT EDIT!

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	strand.proto

It has these top-level messages:
	PingRequest
	PingResponse
	WriteRequest
	ReadRequest
	WriteResponse
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PingRequest struct {
}

func (m *PingRequest) Reset()                    { *m = PingRequest{} }
func (m *PingRequest) String() string            { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()               {}
func (*PingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type PingResponse struct {
}

func (m *PingResponse) Reset()                    { *m = PingResponse{} }
func (m *PingResponse) String() string            { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()               {}
func (*PingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type WriteRequest struct {
	Stream   string `protobuf:"bytes,1,opt,name=stream" json:"stream,omitempty"`
	Messages []byte `protobuf:"bytes,2,opt,name=messages,proto3" json:"messages,omitempty"`
}

func (m *WriteRequest) Reset()                    { *m = WriteRequest{} }
func (m *WriteRequest) String() string            { return proto.CompactTextString(m) }
func (*WriteRequest) ProtoMessage()               {}
func (*WriteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ReadRequest struct {
	Stream string `protobuf:"bytes,1,opt,name=stream" json:"stream,omitempty"`
	Offset uint64 `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type WriteResponse struct {
	Ok bool `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
}

func (m *WriteResponse) Reset()                    { *m = WriteResponse{} }
func (m *WriteResponse) String() string            { return proto.CompactTextString(m) }
func (*WriteResponse) ProtoMessage()               {}
func (*WriteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func init() {
	proto.RegisterType((*PingRequest)(nil), "api.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "api.PingResponse")
	proto.RegisterType((*WriteRequest)(nil), "api.WriteRequest")
	proto.RegisterType((*ReadRequest)(nil), "api.ReadRequest")
	proto.RegisterType((*WriteResponse)(nil), "api.WriteResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Strand service

type StrandClient interface {
	Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error)
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type strandClient struct {
	cc *grpc.ClientConn
}

func NewStrandClient(cc *grpc.ClientConn) StrandClient {
	return &strandClient{cc}
}

func (c *strandClient) Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error) {
	out := new(WriteResponse)
	err := grpc.Invoke(ctx, "/api.Strand/Write", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strandClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := grpc.Invoke(ctx, "/api.Strand/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Strand service

type StrandServer interface {
	Write(context.Context, *WriteRequest) (*WriteResponse, error)
	Ping(context.Context, *PingRequest) (*PingResponse, error)
}

func RegisterStrandServer(s *grpc.Server, srv StrandServer) {
	s.RegisterService(&_Strand_serviceDesc, srv)
}

func _Strand_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrandServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Strand/Write",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrandServer).Write(ctx, req.(*WriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Strand_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrandServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Strand/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrandServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Strand_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Strand",
	HandlerType: (*StrandServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Write",
			Handler:    _Strand_Write_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Strand_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("strand.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x50, 0xb1, 0x4e, 0x80, 0x30,
	0x14, 0x0c, 0x88, 0x04, 0x1f, 0x85, 0xc8, 0x1b, 0x0c, 0x61, 0xd1, 0x74, 0x32, 0x31, 0xe9, 0xa0,
	0xb3, 0x8b, 0x5f, 0x60, 0xea, 0xe0, 0x5c, 0xc3, 0x83, 0x10, 0x03, 0x45, 0x5e, 0xfd, 0x7f, 0x6b,
	0x69, 0x4c, 0x37, 0xb7, 0xde, 0xdd, 0xeb, 0xe5, 0xee, 0x40, 0xb0, 0x3b, 0xcc, 0x36, 0xaa, 0xfd,
	0xb0, 0xce, 0xe2, 0x85, 0xd9, 0x17, 0xd9, 0x40, 0xfd, 0xba, 0x6c, 0xb3, 0xa6, 0xaf, 0x6f, 0x62,
	0x27, 0x5b, 0x10, 0x27, 0xe4, 0xdd, 0x6e, 0x4c, 0xf2, 0x05, 0xc4, 0xfb, 0xb1, 0x38, 0x8a, 0x3a,
	0xde, 0x40, 0xe9, 0x3d, 0xc8, 0xac, 0x7d, 0x76, 0x97, 0xdd, 0x5f, 0xe9, 0x88, 0x70, 0x80, 0x6a,
	0x25, 0x66, 0x33, 0x13, 0xf7, 0xb9, 0x57, 0x84, 0xfe, 0xc3, 0xf2, 0x19, 0x6a, 0x4d, 0x66, 0xfc,
	0xcf, 0xc2, 0xf3, 0x76, 0x9a, 0x98, 0x5c, 0x30, 0x28, 0x74, 0x44, 0xf2, 0x16, 0x9a, 0x18, 0xe1,
	0xcc, 0x84, 0x2d, 0xe4, 0xf6, 0x33, 0x7c, 0xae, 0xb4, 0x7f, 0x3d, 0x12, 0x94, 0x6f, 0xa1, 0x17,
	0x2a, 0xb8, 0x0c, 0xa7, 0xd8, 0x29, 0xdf, 0x4d, 0xa5, 0xc9, 0x07, 0x4c, 0xa9, 0xe8, 0xf4, 0x00,
	0xc5, 0x6f, 0x5b, 0xbc, 0x0e, 0x5a, 0xb2, 0xc3, 0xd0, 0x25, 0xcc, 0x79, 0xfc, 0x51, 0x86, 0xd5,
	0x9e, 0x7e, 0x02, 0x00, 0x00, 0xff, 0xff, 0xec, 0x0a, 0x89, 0x5a, 0x45, 0x01, 0x00, 0x00,
}
